2021-09-03 10:20:07,504: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.
2021-09-03 10:22:19,577: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 1083, in send_static_file
    return send_from_directory(
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2021-09-03 10:32:57,513: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 8496536):
Error Message:ERROR:  syntax error at or near ")"
LINE 13: CREATE TABLE epa_air_quality(date, )
                                            ^
SQL state: 42601
Character: 513
2021-09-03 10:33:21,304: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 879583):
Error Message:ERROR:  syntax error at or near "site_name"
LINE 17:  site_name VARCHAR NOT NULL,
          ^
SQL state: 42601
Character: 550
2021-09-03 10:34:53,650: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5887817):
Error Message:ERROR:  syntax error at or near ")"
LINE 23: );
         ^
SQL state: 42601
Character: 688
2021-09-03 10:35:11,617: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3571651):
Error Message:ERROR:  syntax error at or near "INSERT"
LINE 56: INSERT INTO epa_site_location (site_id, site_name, site_lati...
         ^
SQL state: 42601
Character: 1639
2021-09-03 10:35:36,244: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 2013420):
Error Message:ERROR:  syntax error at or near "Avenue"
LINE 58: VALUES(60070008, Chico_East Avenue, 39.76168, -121.84047, Bu...
                                     ^
SQL state: 42601
Character: 1768
2021-09-03 10:35:44,954: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3800142):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:38,966: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5251799):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:39,719: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 6260898):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:40,160: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 21343):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:40,303: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5942441):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:40,458: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5695509):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:40,678: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 7653155):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:40,817: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 1058740):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:40,956: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 9799270):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:36:45,811: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 8597475):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  column "date" is of type date but expression is of type integer
LINE 56: VALUES (2021-08-07, 60070008, 27, 25);
                 ^
HINT:  You will need to rewrite or cast the expression.
SQL state: 42804
Character: 1613
2021-09-03 10:37:48,721: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3018137):
Error Message:ERROR:  syntax error at or near "'
INSERT INTO epa_site_location (site_id, site_name, site_latitude, site_longitude, county, "state")
VALUES(60070008, '"
LINE 57: '
         ^
SQL state: 42601
Character: 1646
2021-09-03 10:37:53,663: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3791702):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  insert or update on table "epa_air_quality" violates foreign key constraint "epa_air_quality_site_id_fkey"
DETAIL:  Key (site_id)=(60070008) is not present in table "epa_site_location".
SQL state: 23503
2021-09-03 10:38:46,967: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 1452254):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  insert or update on table "epa_air_quality" violates foreign key constraint "epa_air_quality_site_id_fkey"
DETAIL:  Key (site_id)=(60070008) is not present in table "epa_site_location".
SQL state: 23503
2021-09-03 10:40:01,764: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 638649):
Error Message:ERROR:  syntax error at or near "INSERT"
LINE 80: INSERT INTO epa_site_location VALUES (60070001, 'Central Mar...
         ^
SQL state: 42601
Character: 2576
2021-09-03 10:40:15,964: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 6342400):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  CREATE DATABASE cannot run inside a transaction block
SQL state: 25001
2021-09-03 10:40:57,797: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5027254):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  insert or update on table "epa_air_quality" violates foreign key constraint "epa_air_quality_site_id_fkey"
DETAIL:  Key (site_id)=(60070008) is not present in table "epa_site_location".
SQL state: 23503
2021-09-03 10:41:29,312: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 2785311):
Error Message:NOTICE:  table "epa_air_quality" does not exist, skipping
NOTICE:  table "epa_site_location" does not exist, skipping

ERROR:  column "site_longitude" of relation "epa_site_location" does not exist
LINE 55: ...site_location (site_id, site_name, site_latitude, site_longi...
                                                              ^
SQL state: 42703
Character: 1579
2021-09-03 10:41:41,550: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 8810005):
Error Message:ERROR:  relation "epa_site_location" does not exist
LINE 1: INSERT INTO epa_site_location (site_id, site_name, site_lati...
                    ^
SQL state: 42P01
Character: 13
2021-09-03 10:41:58,517: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 8271255):
Error Message:ERROR:  column "site_longitude" of relation "epa_site_location" does not exist
LINE 1: ...site_location (site_id, site_name, site_latitude, site_longi...
                                                             ^
SQL state: 42703
Character: 67
2021-09-03 10:42:30,091: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3563225):
Error Message:ERROR:  syntax error at or near "INTO"
LINE 57: INSERT INTO epa_site_location (site_id, site_name, site_lati...
                ^
SQL state: 42601
Character: 1583
2021-09-03 10:43:30,283: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 9588482):
Error Message:ERROR:  could not open file "/Users/lawrencedlin/classes/msds691/Data/epa_site_location.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
SQL state: 58P01
2021-09-03 10:57:16,713: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 7112676):
Error Message:ERROR:  syntax error at or near "lity"
LINE 1: lity
        ^
SQL state: 42601
Character: 1
2021-09-03 11:32:54,358: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3083940):
Error Message:ERROR:  syntax error at or near "TABLE"
LINE 108: DELETE TABLE epa_site_location;
                 ^
SQL state: 42601
Character: 3295
2021-09-03 11:33:14,086: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 8224044):
Error Message:ERROR:  cannot drop table epa_site_location because other objects depend on it
DETAIL:  constraint epa_air_quality_site_id_fkey on table epa_air_quality depends on table epa_site_location
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
SQL state: 2BP01
2021-09-03 11:39:20,472: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5960340):
Error Message:ERROR:  table "epa_site_location" does not exist
SQL state: 42P01
2021-09-03 11:39:23,175: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 6290227):
Error Message:ERROR:  table "epa_site_location" does not exist
SQL state: 42P01
2021-09-03 11:39:37,635: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3449086):
Error Message:ERROR:  table "epa_site_location" does not exist
SQL state: 42P01
2021-09-03 11:39:39,180: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5098417):
Error Message:ERROR:  table "epa_site_location" does not exist
SQL state: 42P01
2021-09-03 11:59:02,004: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 3765155):
Error Message:ERROR:  syntax error at or near "date"
LINE 128: ORDER date ASC;
                ^
SQL state: 42601
Character: 3757
2021-09-03 11:59:08,593: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 6927516):
Error Message:ERROR:  syntax error at or near "'date'"
LINE 128: ORDER 'date' ASC;
                ^
SQL state: 42601
Character: 3757
2021-09-03 12:00:11,356: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 5018387):
Error Message:ERROR:  column "date" does not exist
LINE 119: SELECT date, 
                 ^
SQL state: 42703
Character: 3604
2021-09-03 12:00:30,204: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 6105666):
Error Message:ERROR:  non-integer constant in ORDER BY
LINE 131: ORDER BY 'date' ASC;
                   ^
SQL state: 42601
Character: 3824
2021-09-03 12:01:54,047: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #1 - CONN:6829967(Query-id: 8166816):
Error Message:ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 131: ORDER BY date ASC;
                   ^
SQL state: 42P10
Character: 3824
2021-09-03 12:03:55,747: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 1083, in send_static_file
    return send_from_directory(
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2021-09-03 12:04:55,543: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 1083, in send_static_file
    return send_from_directory(
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2021-09-03 12:05:11,564: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 1083, in send_static_file
    return send_from_directory(
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
